### PR TITLE
feat(Terser): code minification migration

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This fixes webpack build in production mode
For more details, see @webpack/webpack#7908

Thanks!

```
ERROR in main-server.js from UglifyJs
    Unexpected token: name (NodeList) [./node_modules/domino/lib/NodeList.es6.js:4,0][main-server.js:99960,23]
```

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@Flood Good point, I'll review and asap.
Thanks!

**Comment by peterblazejewicz** [comment]
@Flood 
Updated and squashed with changes.
Thanks again!

**Comment by MarkPieszak** [comment]
Got latest and merging it in! You rock @peterblazejewicz 	🎸🎸🎸🎸

**Comment by peterblazejewicz** [comment]
YAW

**Pull request merged**
